branches:
  only:
    - master

sudo: required

services:
  - docker

env:
  global:
    - NAME=zer0i3/xss-receiver

script:
  - docker build -t ${NAME}:latest .

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin;
    docker push ${NAME}:latest;